codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 1
    wait_for_ci: false
coverage:
  precision: 2
  range: "0...100"
  round: down
  status:
    changes: false
    patch: false
    project: false
  ignore:
    - test/.*
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: true
      method: true
comment:
  behavior: default
  layout: header, diff
  require_changes: false
