codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 4
    wait_for_ci: yes
coverage:
  precision: 2
  range: "0...100"
  round: down
  status:
    changes: false
    patch: false
    project: false
  ignore:
    - test/.*
  notify:
    irc:
      default:
        server: "chat.freenode.net"
        channel: "#rawspeed"
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
comment:
  behavior: default
  layout: header, diff
  require_changes: false
